# Generated by Django 6.0.6 on 2026-07-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("user", "question"), name="unique_user_question_answer"
            ),
        ),
    ]
