# Generated by Django 6.0.6 on 2026-07-15 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_hub", "0002_useranswer_unique_user_question_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PraticeExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("instructions", models.TextField()),
                ("expected_query", models.TextField()),
                ("dataset", models.JSONField()),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study_hub.topics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PraticeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_query", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pratice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study_hub.praticeexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Pratices",
        ),
    ]
